### PR TITLE
fix(lite-doc): lite doc add setting virtual addr and physic addr inte…

### PR DESCRIPTION
**Pull request by chenqy4933**
…rface

### CODE REVIEW

**Comment by chenqy4933** [comment]
@MegChai plz review, thanks!

**Comment by MegChai** [comment]
麻烦修一下 CI warning:

```
/home/runner/work/Documentation/Documentation/source/user-guide/deployment/lite/interface/python.rst:983: WARNING: Error in "code-block" directive:
maximum 1 argument(s) allowed, 18 supplied.

.. code-block:: python
looking for now-outdated files... none found
    def register_memory_pair(
            vir_ptr, phy_ptr, length, device, backend=LiteBackend.LITE_DEFAULT
        ):
    def clear_memory_pair(vir_ptr, phy_ptr, device, backend=LiteBackend.LITE_DEFAULT):
    def lookup_physic_ptr(vir_ptr, device, backend=LiteBackend.LITE_DEFAULT):
```

应该是少了换行或者缩进不对

**Comment by MegChai** [comment]
pin @chenqy4933

**Review by MegChai — APPROVED** [review]
LGTM.

**Pull request merged**
